# Create a GitHub Actions workflow YAML file (e.g., main.yml) in the .github/workflows directory
# This workflow will run only on the main branch

name: Set Secret and Run Python Script

on:
  pull_request:
    branches:
      - main
  push:
    paths: 
      - CHANGELOG.md
    branches:
      - main

jobs:
  set-secret-and-run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python create_release.py