name: 'Automated Releases'
description: 'Automate Release Publication based on a CHANGELOG.md file and a VERSION.txt'
icon: anchor
color: blue
inputs:
  GITHUB_API_URL:
    description: 'Github API / Enterprise Server URL'
    required: true
    default: "https://api.github.com"
  CHANGELOG_PATH_FILE:  # id of input
    description: 'Path to the changelog.md'
    required: true
    default: 'CHANGELOG.md'
  VERSION_PATH_FILE:  # id of input
    description: 'Path to the VERSION.txt file'
    required: true
    default: 'VERSION.txt'
  GIT_PERSONAL_ACCESS_TOKEN:
    description: 'Personal access token to access Github API'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: devops/auto-releases
        token: ${{ inputs.GIT_PERSONAL_ACCESS_TOKEN }} 
        path: autorelease
        
    - name: View files
      shell: bash
      run: ls
    - name: View Directory
      shell: bash
      run: pwd


    - name: Install Requirements
      shell: bash
      run: pip install -r requirements.txt


    - name: Run Python script
      shell: bash
      run: python3 create_release.py
      env: 
        CHANGELOG_PATH_FILE: ../${{ inputs.CHANGELOG_PATH_FILE }}
        VERSION_PATH_FILE: ../${{ inputs.VERSION_PATH_FILE }}
        GIT_PERSONAL_ACCESS_TOKEN: ${{ inputs.GIT_PERSONAL_ACCESS_TOKEN }} 
        GITHUB_API_URL: ${{ inputs.GITHUB_API_URL }}
